// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

// Configuration that works with rustc < 1.71.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    subscription
    (
        init => init
        depositToken => deposit_token
        withdrawToken => withdraw_token
        subscribeToMultipleServices => subscribe_to_multiple_services
        unsubscribeFromMultipleServices => unsubscribe_from_multiple_services
        getTokenPairValue => get_token_pair_value
        sendTokens => send_tokens
        clearLastVec => clear_last_vec
        getNetflix => netflix
        getTokensCount => tokens_count
        getTokens => tokens
        getLPAddress => lp_address
        getIds => id
        getServicesCount => services_count
        getServices => services
        getBalance => balance
        getSubscription => subscription
        getSafePriceView => safe_price_view
        getLastPaymentVec => last_payment_vec
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
